# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

# baseURL = "https://sebastiankraska.com/"
defaultContentLanguage = "en"

enableRobotsTXT = true
summaryLength = 0

[pagination]
  pagerSize = 10

[outputs]
  # home = ["HTML", "RSS", "JSON"]
  home = ["HTML", "RSS", "JSON", "HeadlessCMSConfig"]

[privacy]
  [privacy.vimeo]
    enableDNT = true
  [privacy.x]
    enableDNT = true
  [privacy.youTube]
    privacyEnhanced = true

[services]
  [services.x]
    disableInlineCSS = true

 [taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

